//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeTongji {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeTongji.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreements.
        /// </summary>
        public static string About_AgreementLink {
            get {
                return ResourceManager.GetString("About_AgreementLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone.
        /// </summary>
        public static string About_PlatformName {
            get {
                return ResourceManager.GetString("About_PlatformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate us.
        /// </summary>
        public static string About_Rate {
            get {
                return ResourceManager.GetString("About_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official website.
        /// </summary>
        public static string About_ViewWebsite {
            get {
                return ResourceManager.GetString("About_ViewWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Activity_AppBarFavoriteText {
            get {
                return ResourceManager.GetString("Activity_AppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Activity_AppBarLikeText {
            get {
                return ResourceManager.GetString("Activity_AppBarLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Activity_AppBarParticipateText {
            get {
                return ResourceManager.GetString("Activity_AppBarParticipateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        public static string Activity_AppBarUnfavoriteText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnfavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike.
        /// </summary>
        public static string Activity_AppBarUnlikeText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnlikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Activity_AppBarUnparticipateText {
            get {
                return ResourceManager.GetString("Activity_AppBarUnparticipateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Activity_EventDetails {
            get {
                return ResourceManager.GetString("Activity_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Activity_EventIllustration {
            get {
                return ResourceManager.GetString("Activity_EventIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string Activity_EventIntroduction {
            get {
                return ResourceManager.GetString("Activity_EventIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures..
        /// </summary>
        public static string Activity_NoIllustrationPrompt {
            get {
                return ResourceManager.GetString("Activity_NoIllustrationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Activity_Source {
            get {
                return ResourceManager.GetString("Activity_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreements.
        /// </summary>
        public static string Agreement_PageTitle {
            get {
                return ResourceManager.GetString("Agreement_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string CalendarNode_Today {
            get {
                return ResourceManager.GetString("CalendarNode_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CampusInfo_AppBarRefreshText {
            get {
                return ResourceManager.GetString("CampusInfo_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommends.
        /// </summary>
        public static string CampusInfo_AroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_AroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string CampusInfo_AroundNewsWithTicketPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_AroundNewsWithTicketPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Notices.
        /// </summary>
        public static string CampusInfo_ClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_ClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingMoreAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingMoreClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingMoreOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingMoreTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingMoreTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CampusInfo_LoadingTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadingTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string CampusInfo_LoadMoreAroundNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreAroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string CampusInfo_LoadMoreClubNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string CampusInfo_LoadMoreOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string CampusInfo_LoadMoreTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_LoadMoreTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CampusInfo_NoAroundNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoAroundNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CampusInfo_NoClubNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoClubNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CampusInfo_NoOfficialNotesPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoOfficialNotesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CampusInfo_NoTongjiNewsPrompt {
            get {
                return ResourceManager.GetString("CampusInfo_NoTongjiNewsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Note.
        /// </summary>
        public static string CampusInfo_OfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_OfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus News.
        /// </summary>
        public static string CampusInfo_PageTitle {
            get {
                return ResourceManager.GetString("CampusInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new group notice.
        /// </summary>
        public static string CampusInfo_ReceiveANewGroupNotice {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveANewGroupNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new official note.
        /// </summary>
        public static string CampusInfo_ReceiveANewOfficialNote {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveANewOfficialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new recommend.
        /// </summary>
        public static string CampusInfo_ReceiveANewRecommend {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveANewRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new Tongji news.
        /// </summary>
        public static string CampusInfo_ReceiveANewTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveANewTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new group notices.
        /// </summary>
        public static string CampusInfo_ReceiveNewGroupNotices {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveNewGroupNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new official notes.
        /// </summary>
        public static string CampusInfo_ReceiveNewOfficialNotes {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveNewOfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new recommends.
        /// </summary>
        public static string CampusInfo_ReceiveNewRecommends {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveNewRecommends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new Tongji news.
        /// </summary>
        public static string CampusInfo_ReceiveNewTongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_ReceiveNewTongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongji News.
        /// </summary>
        public static string CampusInfo_TongjiNews {
            get {
                return ResourceManager.GetString("CampusInfo_TongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Common_AppBarFavoriteText {
            get {
                return ResourceManager.GetString("Common_AppBarFavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Common_AppBarLikeText {
            get {
                return ResourceManager.GetString("Common_AppBarLikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        public static string Common_AppBarUnfavoriteText {
            get {
                return ResourceManager.GetString("Common_AppBarUnfavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike.
        /// </summary>
        public static string Common_AppBarUnlikeText {
            get {
                return ResourceManager.GetString("Common_AppBarUnlikeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to exit WeTongji?.
        /// </summary>
        public static string Common_ExitAppPromptContent {
            get {
                return ResourceManager.GetString("Common_ExitAppPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed, please retry..
        /// </summary>
        public static string Common_FailurePrompt {
            get {
                return ResourceManager.GetString("Common_FailurePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string Common_JustNow {
            get {
                return ResourceManager.GetString("Common_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading pic....
        /// </summary>
        public static string Common_LoadingPicture {
            get {
                return ResourceManager.GetString("Common_LoadingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Loading pic failed. Click to retry.).
        /// </summary>
        public static string Common_LoadPictureFailedPrompt {
            get {
                return ResourceManager.GetString("Common_LoadPictureFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in first..
        /// </summary>
        public static string Common_LogInFirstPrompt {
            get {
                return ResourceManager.GetString("Common_LogInFirstPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Common_Prompt {
            get {
                return ResourceManager.GetString("Common_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in on other devices? Please sign in again..
        /// </summary>
        public static string Common_SignInOnOtherPlatformPrompt {
            get {
                return ResourceManager.GetString("Common_SignInOnOtherPlatformPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        public static string Common_WithinOneHourTemplate {
            get {
                return ResourceManager.GetString("Common_WithinOneHourTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string Common_WithinSixHoursTemplate {
            get {
                return ResourceManager.GetString("Common_WithinSixHoursTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string Common_WithinTwoHours {
            get {
                return ResourceManager.GetString("Common_WithinTwoHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course detail.
        /// </summary>
        public static string CourseDetail_CourseHeader {
            get {
                return ResourceManager.GetString("CourseDetail_CourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        public static string CourseDetail_CourseNO {
            get {
                return ResourceManager.GetString("CourseDetail_CourseNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam.
        /// </summary>
        public static string CourseDetail_ExamHeader {
            get {
                return ResourceManager.GetString("CourseDetail_ExamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class hours.
        /// </summary>
        public static string CourseDetail_Hours {
            get {
                return ResourceManager.GetString("CourseDetail_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CourseDetail_LoadingCourseDetail {
            get {
                return ResourceManager.GetString("CourseDetail_LoadingCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CourseDetail_LoadingExam {
            get {
                return ResourceManager.GetString("CourseDetail_LoadingExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string CourseDetail_Location {
            get {
                return ResourceManager.GetString("CourseDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CourseDetail_NoCoursePrompt {
            get {
                return ResourceManager.GetString("CourseDetail_NoCoursePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string CourseDetail_NoExamPrompt {
            get {
                return ResourceManager.GetString("CourseDetail_NoExamPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CourseDetail_Points {
            get {
                return ResourceManager.GetString("CourseDetail_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string CourseDetail_Teacher {
            get {
                return ResourceManager.GetString("CourseDetail_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string CourseDetail_Time {
            get {
                return ResourceManager.GetString("CourseDetail_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri..
        /// </summary>
        public static string DayOfWeekAbbr_Friday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon..
        /// </summary>
        public static string DayOfWeekAbbr_Monday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat..
        /// </summary>
        public static string DayOfWeekAbbr_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun..
        /// </summary>
        public static string DayOfWeekAbbr_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thur..
        /// </summary>
        public static string DayOfWeekAbbr_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tues..
        /// </summary>
        public static string DayOfWeekAbbr_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed..
        /// </summary>
        public static string DayOfWeekAbbr_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeekAbbr_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditPersonalProfile_AppBarSaveText {
            get {
                return ResourceManager.GetString("EditPersonalProfile_AppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string EditPersonalProfile_Avatar {
            get {
                return ResourceManager.GetString("EditPersonalProfile_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to go back without saving?.
        /// </summary>
        public static string EditPersonalProfile_DiscardAndReturnPrompt {
            get {
                return ResourceManager.GetString("EditPersonalProfile_DiscardAndReturnPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EditPersonalProfile_Email {
            get {
                return ResourceManager.GetString("EditPersonalProfile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EditPersonalProfile_EnterEmail {
            get {
                return ResourceManager.GetString("EditPersonalProfile_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your QQ.
        /// </summary>
        public static string EditPersonalProfile_EnterQQ {
            get {
                return ResourceManager.GetString("EditPersonalProfile_EnterQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your sina weibo.
        /// </summary>
        public static string EditPersonalProfile_EnterSinaWeibo {
            get {
                return ResourceManager.GetString("EditPersonalProfile_EnterSinaWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone.
        /// </summary>
        public static string EditPersonalProfile_EnterTel {
            get {
                return ResourceManager.GetString("EditPersonalProfile_EnterTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditPersonalProfile_PageTitle {
            get {
                return ResourceManager.GetString("EditPersonalProfile_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        public static string EditPersonalProfile_QQ {
            get {
                return ResourceManager.GetString("EditPersonalProfile_QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving profile failed, please retry..
        /// </summary>
        public static string EditPersonalProfile_SavePersonalProfileFailedPrompt {
            get {
                return ResourceManager.GetString("EditPersonalProfile_SavePersonalProfileFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sina weibo.
        /// </summary>
        public static string EditPersonalProfile_SinaWeibo {
            get {
                return ResourceManager.GetString("EditPersonalProfile_SinaWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string EditPersonalProfile_Tel {
            get {
                return ResourceManager.GetString("EditPersonalProfile_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating avatar failed, please retry..
        /// </summary>
        public static string EditPersonalProfile_UpdateAvatarFailedPrompt {
            get {
                return ResourceManager.GetString("EditPersonalProfile_UpdateAvatarFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ForgotPassword_AppBarSendText {
            get {
                return ResourceManager.GetString("ForgotPassword_AppBarSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string ForgotPassword_EnterName {
            get {
                return ResourceManager.GetString("ForgotPassword_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter student ID.
        /// </summary>
        public static string ForgotPassword_EnterStudentNO {
            get {
                return ResourceManager.GetString("ForgotPassword_EnterStudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name and student ID do not match..
        /// </summary>
        public static string ForgotPassword_IdNameDismatchPrompt {
            get {
                return ResourceManager.GetString("ForgotPassword_IdNameDismatchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ForgotPassword_Name {
            get {
                return ResourceManager.GetString("ForgotPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not exist..
        /// </summary>
        public static string ForgotPassword_NoAccountPrompt {
            get {
                return ResourceManager.GetString("ForgotPassword_NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been activated..
        /// </summary>
        public static string ForgotPassword_NotActivatedAccountPrompt {
            get {
                return ResourceManager.GetString("ForgotPassword_NotActivatedAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been registered yet..
        /// </summary>
        public static string ForgotPassword_NotRegisteredPrompt {
            get {
                return ResourceManager.GetString("ForgotPassword_NotRegisteredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string ForgotPassword_PageTitle {
            get {
                return ResourceManager.GetString("ForgotPassword_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send a password-reset email to you in a minute..
        /// </summary>
        public static string ForgotPassword_Prompt {
            get {
                return ResourceManager.GetString("ForgotPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string ForgotPassword_StudentNO {
            get {
                return ResourceManager.GetString("ForgotPassword_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string ForgotPassword_SucceededCaption {
            get {
                return ResourceManager.GetString("ForgotPassword_SucceededCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go and check your reset email..
        /// </summary>
        public static string ForgotPassword_SucceededText {
            get {
                return ResourceManager.GetString("ForgotPassword_SucceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ImageViewer_AppBarSaveText {
            get {
                return ResourceManager.GetString("ImageViewer_AppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed..
        /// </summary>
        public static string ImageViewer_SaveFailed {
            get {
                return ResourceManager.GetString("ImageViewer_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save picture successfully..
        /// </summary>
        public static string ImageViewer_SaveSucceeded {
            get {
                return ResourceManager.GetString("ImageViewer_SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password, please try again..
        /// </summary>
        public static string MainPage_AccountPasswordDismatchPrompt {
            get {
                return ResourceManager.GetString("MainPage_AccountPasswordDismatchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string MainPage_Activities {
            get {
                return ResourceManager.GetString("MainPage_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is {0} now, \&quot;{1}\&quot; will start in {2} minutes..
        /// </summary>
        public static string MainPage_ActivityExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ActivityExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string MainPage_Alarms {
            get {
                return ResourceManager.GetString("MainPage_Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainPage_AppBarAboutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MainPage_AppBarFeedbackText {
            get {
                return ResourceManager.GetString("MainPage_AppBarFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hottest.
        /// </summary>
        public static string MainPage_AppBarHotEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarHotEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Latest.
        /// </summary>
        public static string MainPage_AppBarLatestEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarLatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string MainPage_AppBarLoginText {
            get {
                return ResourceManager.GetString("MainPage_AppBarLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Most Recent.
        /// </summary>
        public static string MainPage_AppBarRecentEvents {
            get {
                return ResourceManager.GetString("MainPage_AppBarRecentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainPage_AppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string MainPage_AppBarRegisterText {
            get {
                return ResourceManager.GetString("MainPage_AppBarRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainPage_AppBarSettingsText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share by email.
        /// </summary>
        public static string MainPage_AppBarShareToFriendsByMail {
            get {
                return ResourceManager.GetString("MainPage_AppBarShareToFriendsByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string MainPage_AppBarSignOutText {
            get {
                return ResourceManager.GetString("MainPage_AppBarSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MainPage_AppBarViewAllPeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_AppBarViewAllPeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommends.
        /// </summary>
        public static string MainPage_AroundNews {
            get {
                return ResourceManager.GetString("MainPage_AroundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string MainPage_AutoLoginPrompt {
            get {
                return ResourceManager.GetString("MainPage_AutoLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus News.
        /// </summary>
        public static string MainPage_CampusInfo {
            get {
                return ResourceManager.GetString("MainPage_CampusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MainPage_CancelAutoLogin {
            get {
                return ResourceManager.GetString("MainPage_CancelAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Notices.
        /// </summary>
        public static string MainPage_ClubNews {
            get {
                return ResourceManager.GetString("MainPage_ClubNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in failed, please retry..
        /// </summary>
        public static string MainPage_CommonLoginFailedPrompt {
            get {
                return ResourceManager.GetString("MainPage_CommonLoginFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to sign out?.
        /// </summary>
        public static string MainPage_ConfirmSignOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_ConfirmSignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is {0} now, \&quot;{1}\&quot;will start in {2} minutes..
        /// </summary>
        public static string MainPage_CourseExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_CourseExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string MainPage_EnterPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your ID.
        /// </summary>
        public static string MainPage_EnterStudentNOPrompt {
            get {
                return ResourceManager.GetString("MainPage_EnterStudentNOPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is {0} now, the exam of \&quot;{1}\&quot; will start in {2} minutes..
        /// </summary>
        public static string MainPage_ExamExpiredPromptContentTemplate {
            get {
                return ResourceManager.GetString("MainPage_ExamExpiredPromptContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        public static string MainPage_Feed {
            get {
                return ResourceManager.GetString("MainPage_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string MainPage_ForgotPasswordLink {
            get {
                return ResourceManager.GetString("MainPage_ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid, please retry..
        /// </summary>
        public static string MainPage_InvalidPasswordPrompt {
            get {
                return ResourceManager.GetString("MainPage_InvalidPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string MainPage_LoadingAlarms {
            get {
                return ResourceManager.GetString("MainPage_LoadingAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more....
        /// </summary>
        public static string MainPage_LoadingMoreEvents {
            get {
                return ResourceManager.GetString("MainPage_LoadingMoreEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string MainPage_LoadMoreActivities {
            get {
                return ResourceManager.GetString("MainPage_LoadMoreActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout, please retry..
        /// </summary>
        public static string MainPage_LoginTimeOutPrompt {
            get {
                return ResourceManager.GetString("MainPage_LoginTimeOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My agenda.
        /// </summary>
        public static string MainPage_MyAgenda {
            get {
                return ResourceManager.GetString("MainPage_MyAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favorites.
        /// </summary>
        public static string MainPage_MyFavorite {
            get {
                return ResourceManager.GetString("MainPage_MyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID is invalid, please retry..
        /// </summary>
        public static string MainPage_NoAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string MainPage_NoActivitiesPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoActivitiesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string MainPage_NoArrangementTodayFirstLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodayFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arrangement.
        /// </summary>
        public static string MainPage_NoArrangementTodaySecondLine {
            get {
                return ResourceManager.GetString("MainPage_NoArrangementTodaySecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detail info.
        /// </summary>
        public static string MainPage_NoPeopleOfWeekPrompt {
            get {
                return ResourceManager.GetString("MainPage_NoPeopleOfWeekPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has not been activated..
        /// </summary>
        public static string MainPage_NotActivatedAccountPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotActivatedAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign up for your account..
        /// </summary>
        public static string MainPage_NotRegisteredPrompt {
            get {
                return ResourceManager.GetString("MainPage_NotRegisteredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Note.
        /// </summary>
        public static string MainPage_OfficialNotes {
            get {
                return ResourceManager.GetString("MainPage_OfficialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        public static string MainPage_Participants {
            get {
                return ResourceManager.GetString("MainPage_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MainPage_Password {
            get {
                return ResourceManager.GetString("MainPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string MainPage_PasswordLengthErrorPromptCaption {
            get {
                return ResourceManager.GetString("MainPage_PasswordLengthErrorPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 6 characters are required..
        /// </summary>
        public static string MainPage_PasswordLengthErrorPromptText {
            get {
                return ResourceManager.GetString("MainPage_PasswordLengthErrorPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Star.
        /// </summary>
        public static string MainPage_PeopleOfWeek {
            get {
                return ResourceManager.GetString("MainPage_PeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new activity.
        /// </summary>
        public static string MainPage_ReceiveANewActivityTemplate {
            get {
                return ResourceManager.GetString("MainPage_ReceiveANewActivityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new activities.
        /// </summary>
        public static string MainPage_ReceiveNewActivitiesTemplate {
            get {
                return ResourceManager.GetString("MainPage_ReceiveNewActivitiesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m using WeTongji - the campus mobile application for Tongji, with the help of which every student could manage his agenda, aware of every school news. Never miss any single activity on campus any more. Go to download(http://we.tongji.edu.cn).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailBody {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation of WeTongji(Windows Phone).
        /// </summary>
        public static string MainPage_ShareToFriendsEmailSubject {
            get {
                return ResourceManager.GetString("MainPage_ShareToFriendsEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string MainPage_StudentNO {
            get {
                return ResourceManager.GetString("MainPage_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong student ID.
        /// </summary>
        public static string MainPage_StudentNOErrorPromptCaption {
            get {
                return ResourceManager.GetString("MainPage_StudentNOErrorPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID must consist of all numbers..
        /// </summary>
        public static string MainPage_StudentNOErrorPromptText {
            get {
                return ResourceManager.GetString("MainPage_StudentNOErrorPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongji News.
        /// </summary>
        public static string MainPage_TongjiNews {
            get {
                return ResourceManager.GetString("MainPage_TongjiNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m using WeTongji(Windows Phone v{2}) on {0} {1}..
        /// </summary>
        public static string MainPage_UserFeedBackEmailBodyTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Feedback]WeTongji(Windows Phone v{0}).
        /// </summary>
        public static string MainPage_UserFeedBackEmailSubjectTemplate {
            get {
                return ResourceManager.GetString("MainPage_UserFeedBackEmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string MainPage_ViewPeopleOfWeekDetail {
            get {
                return ResourceManager.GetString("MainPage_ViewPeopleOfWeekDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string MyAgenda_AppBarTodayText {
            get {
                return ResourceManager.GetString("MyAgenda_AppBarTodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MyAgenda_Loading {
            get {
                return ResourceManager.GetString("MyAgenda_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arrangements today. Time to rest!.
        /// </summary>
        public static string MyAgenda_NoArrangementToday {
            get {
                return ResourceManager.GetString("MyAgenda_NoArrangementToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus News.
        /// </summary>
        public static string MyFavorite_CampusInfo {
            get {
                return ResourceManager.GetString("MyFavorite_CampusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string MyFavorite_EventParticipants {
            get {
                return ResourceManager.GetString("MyFavorite_EventParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string MyFavorite_Events {
            get {
                return ResourceManager.GetString("MyFavorite_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content..
        /// </summary>
        public static string MyFavorite_NoCampusInfoPrompt {
            get {
                return ResourceManager.GetString("MyFavorite_NoCampusInfoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content..
        /// </summary>
        public static string MyFavorite_NoEventsPrompt {
            get {
                return ResourceManager.GetString("MyFavorite_NoEventsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content..
        /// </summary>
        public static string MyFavorite_NoPeopleOfWeekPrompt {
            get {
                return ResourceManager.GetString("MyFavorite_NoPeopleOfWeekPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favorites.
        /// </summary>
        public static string MyFavorite_PageTitle {
            get {
                return ResourceManager.GetString("MyFavorite_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Star.
        /// </summary>
        public static string MyFavorite_PeopleOfWeek {
            get {
                return ResourceManager.GetString("MyFavorite_PeopleOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol. .
        /// </summary>
        public static string MyFavorite_PeopleOfWeekVolPrefix {
            get {
                return ResourceManager.GetString("MyFavorite_PeopleOfWeekVolPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyFavorite_PeopleOfWeekVolSuffix {
            get {
                return ResourceManager.GetString("MyFavorite_PeopleOfWeekVolSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh.
        /// </summary>
        public static string MySettings_AutoRefresh {
            get {
                return ResourceManager.GetString("MySettings_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh resources.
        /// </summary>
        public static string MySettings_AutoRefreshAction {
            get {
                return ResourceManager.GetString("MySettings_AutoRefreshAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update.
        /// </summary>
        public static string MySettings_CheckNewVersion {
            get {
                return ResourceManager.GetString("MySettings_CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed, please retry..
        /// </summary>
        public static string MySettings_CheckNewVersionFailedPrompt {
            get {
                return ResourceManager.GetString("MySettings_CheckNewVersionFailedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string MySettings_ClearImageCache {
            get {
                return ResourceManager.GetString("MySettings_ClearImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to clear cache?.
        /// </summary>
        public static string MySettings_ClearImageCacheConfirmation {
            get {
                return ResourceManager.GetString("MySettings_ClearImageCacheConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string MySettings_ComputingImageCache {
            get {
                return ResourceManager.GetString("MySettings_ComputingImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version:.
        /// </summary>
        public static string MySettings_CurrentVersion {
            get {
                return ResourceManager.GetString("MySettings_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string MySettings_ImageCacheSizeDisplayTemplate {
            get {
                return ResourceManager.GetString("MySettings_ImageCacheSizeDisplayTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to exit.
        /// </summary>
        public static string MySettings_LeaveAppConfirmation {
            get {
                return ResourceManager.GetString("MySettings_LeaveAppConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask when press exit.
        /// </summary>
        public static string MySettings_LeaveAppConfirmationAction {
            get {
                return ResourceManager.GetString("MySettings_LeaveAppConfirmationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version is {0}. Get updated on marketplace?.
        /// </summary>
        public static string MySettings_NewVersionExistsPrompt {
            get {
                return ResourceManager.GetString("MySettings_NewVersionExistsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version already!.
        /// </summary>
        public static string MySettings_NoNewVersionPrompt {
            get {
                return ResourceManager.GetString("MySettings_NoNewVersionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MySettings_PageTitle {
            get {
                return ResourceManager.GetString("MySettings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction:.
        /// </summary>
        public static string NearBy_Introduction {
            get {
                return ResourceManager.GetString("NearBy_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string NearBy_LoadingData {
            get {
                return ResourceManager.GetString("NearBy_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string NearBy_Location {
            get {
                return ResourceManager.GetString("NearBy_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string NearBy_RelatedImages {
            get {
                return ResourceManager.GetString("NearBy_RelatedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string NearBy_Tel {
            get {
                return ResourceManager.GetString("NearBy_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string NearBy_TicketSymbol {
            get {
                return ResourceManager.GetString("NearBy_TicketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PeopleOfWeek_Images {
            get {
                return ResourceManager.GetString("PeopleOfWeek_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string PeopleOfWeek_Introduction {
            get {
                return ResourceManager.GetString("PeopleOfWeek_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Star.
        /// </summary>
        public static string PeopleOfWeek_PageTitle {
            get {
                return ResourceManager.GetString("PeopleOfWeek_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string PeopleOfWeek_Story {
            get {
                return ResourceManager.GetString("PeopleOfWeek_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string PeopleOfWeekList_AppBarRefreshText {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string PeopleOfWeekList_Loading {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All weekly stars..
        /// </summary>
        public static string PeopleOfWeekList_PageTitle {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 new weekly star.
        /// </summary>
        public static string PeopleOfWeekList_ReceiveANewPersonTemplate {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_ReceiveANewPersonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new weekly stars.
        /// </summary>
        public static string PeopleOfWeekList_ReceiveNewPersonsTemplate {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_ReceiveNewPersonsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol..
        /// </summary>
        public static string PeopleOfWeekList_VolPrefix {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_VolPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PeopleOfWeekList_VolSuffix {
            get {
                return ResourceManager.GetString("PeopleOfWeekList_VolSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PersonalProfile_AppBarEditText {
            get {
                return ResourceManager.GetString("PersonalProfile_AppBarEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PersonalProfile_AppBarUpdatePasswordText {
            get {
                return ResourceManager.GetString("PersonalProfile_AppBarUpdatePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add email.
        /// </summary>
        public static string PersonalProfile_CreateEmail {
            get {
                return ResourceManager.GetString("PersonalProfile_CreateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add QQ.
        /// </summary>
        public static string PersonalProfile_CreateQQ {
            get {
                return ResourceManager.GetString("PersonalProfile_CreateQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sina weibo.
        /// </summary>
        public static string PersonalProfile_CreateSinaWeibo {
            get {
                return ResourceManager.GetString("PersonalProfile_CreateSinaWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone.
        /// </summary>
        public static string PersonalProfile_CreateTel {
            get {
                return ResourceManager.GetString("PersonalProfile_CreateTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PersonalProfile_Email {
            get {
                return ResourceManager.GetString("PersonalProfile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed..
        /// </summary>
        public static string PersonalProfile_LoadFailed {
            get {
                return ResourceManager.GetString("PersonalProfile_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string PersonalProfile_Loading {
            get {
                return ResourceManager.GetString("PersonalProfile_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string PersonalProfile_Major {
            get {
                return ResourceManager.GetString("PersonalProfile_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PersonalProfile_PageTitle {
            get {
                return ResourceManager.GetString("PersonalProfile_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        public static string PersonalProfile_QQ {
            get {
                return ResourceManager.GetString("PersonalProfile_QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sina weibo.
        /// </summary>
        public static string PersonalProfile_SinaWeibo {
            get {
                return ResourceManager.GetString("PersonalProfile_SinaWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string PersonalProfile_StudentNO {
            get {
                return ResourceManager.GetString("PersonalProfile_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PersonalProfile_Tel {
            get {
                return ResourceManager.GetString("PersonalProfile_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreements.
        /// </summary>
        public static string SignUp_Agreement {
            get {
                return ResourceManager.GetString("SignUp_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string SignUp_AgreementPrefix {
            get {
                return ResourceManager.GetString("SignUp_AgreementPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string SignUp_AgreementSuffix {
            get {
                return ResourceManager.GetString("SignUp_AgreementSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sign-up. Please sign in..
        /// </summary>
        public static string SignUp_AlreadyRegisteredPrompt {
            get {
                return ResourceManager.GetString("SignUp_AlreadyRegisteredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string SignUp_AppBarOkText {
            get {
                return ResourceManager.GetString("SignUp_AppBarOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some wrong information has been found..
        /// </summary>
        public static string SignUp_BadSignUpInfo {
            get {
                return ResourceManager.GetString("SignUp_BadSignUpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string SignUp_EnterName {
            get {
                return ResourceManager.GetString("SignUp_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string SignUp_EnterPassword {
            get {
                return ResourceManager.GetString("SignUp_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string SignUp_EnterPasswordAgain {
            get {
                return ResourceManager.GetString("SignUp_EnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter student ID.
        /// </summary>
        public static string SignUp_EnterStudentNO {
            get {
                return ResourceManager.GetString("SignUp_EnterStudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree.
        /// </summary>
        public static string SignUp_IAgreeTo {
            get {
                return ResourceManager.GetString("SignUp_IAgreeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name and student ID do not match..
        /// </summary>
        public static string SignUp_IdNameDismatchPrompt {
            get {
                return ResourceManager.GetString("SignUp_IdNameDismatchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SignUp_Name {
            get {
                return ResourceManager.GetString("SignUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not exist..
        /// </summary>
        public static string SignUp_NoAccountPrompt {
            get {
                return ResourceManager.GetString("SignUp_NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp_PageTitle {
            get {
                return ResourceManager.GetString("SignUp_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Fill-in.
        /// </summary>
        public static string SignUp_SecondStep {
            get {
                return ResourceManager.GetString("SignUp_SecondStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string SignUp_StudentNO {
            get {
                return ResourceManager.GetString("SignUp_StudentNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up successfully..
        /// </summary>
        public static string SignUp_SucceededCaption {
            get {
                return ResourceManager.GetString("SignUp_SucceededCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in..
        /// </summary>
        public static string SignUp_SucceededText {
            get {
                return ResourceManager.GetString("SignUp_SucceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string SignUpSuccess_AppBarFinishSigningUpText {
            get {
                return ResourceManager.GetString("SignUpSuccess_AppBarFinishSigningUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongji Email.
        /// </summary>
        public static string SignUpSuccess_BrowseTongjiMail {
            get {
                return ResourceManager.GetString("SignUpSuccess_BrowseTongjiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-up successfully.
        /// </summary>
        public static string SignUpSuccess_PageTitle {
            get {
                return ResourceManager.GetString("SignUpSuccess_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an activation email to your Tongji email. Please go and have a check..
        /// </summary>
        public static string SignUpSuccess_Prompt {
            get {
                return ResourceManager.GetString("SignUpSuccess_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}，Welcome back to WeTongji~.
        /// </summary>
        public static string Toast_AutoLoginSucceededPromptTemplate {
            get {
                return ResourceManager.GetString("Toast_AutoLoginSucceededPromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error, please retry..
        /// </summary>
        public static string Toast_NetworkErrorPrompt {
            get {
                return ResourceManager.GetString("Toast_NetworkErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in successfully..
        /// </summary>
        public static string Toast_SignInSucceededPrompt {
            get {
                return ResourceManager.GetString("Toast_SignInSucceededPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful operation..
        /// </summary>
        public static string Toast_Success {
            get {
                return ResourceManager.GetString("Toast_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeTongji will send an activation email to the Tongji Email only for Tongji students to provide better service..
        /// </summary>
        public static string TongjiMail_BackgroundInfo {
            get {
                return ResourceManager.GetString("TongjiMail_BackgroundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Activate your Tongji Email.
        /// </summary>
        public static string TongjiMail_FirstStep {
            get {
                return ResourceManager.GetString("TongjiMail_FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have activated. Next.
        /// </summary>
        public static string TongjiMail_NextStep {
            get {
                return ResourceManager.GetString("TongjiMail_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string TongjiMail_PageTitle {
            get {
                return ResourceManager.GetString("TongjiMail_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string TongjiMail_Register {
            get {
                return ResourceManager.GetString("TongjiMail_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string UpdatePassword_AppBarSendText {
            get {
                return ResourceManager.GetString("UpdatePassword_AppBarSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string UpdatePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string UpdatePassword_ConfirmNewPasswordErrorPrompt {
            get {
                return ResourceManager.GetString("UpdatePassword_ConfirmNewPasswordErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string UpdatePassword_EnterNewPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string UpdatePassword_EnterNewPasswordAgain {
            get {
                return ResourceManager.GetString("UpdatePassword_EnterNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old password.
        /// </summary>
        public static string UpdatePassword_EnterOldPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string UpdatePassword_NewPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string UpdatePassword_OldPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is wrong..
        /// </summary>
        public static string UpdatePassword_OldPasswordErrorPrompt {
            get {
                return ResourceManager.GetString("UpdatePassword_OldPasswordErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string UpdatePassword_PageTitle {
            get {
                return ResourceManager.GetString("UpdatePassword_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string UpdatePassword_SucceededCaption {
            get {
                return ResourceManager.GetString("UpdatePassword_SucceededCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations. You have already changed your password..
        /// </summary>
        public static string UpdatePassword_SucceededText {
            get {
                return ResourceManager.GetString("UpdatePassword_SucceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official website.
        /// </summary>
        public static string ViewOfficialWebsite_PageTitle {
            get {
                return ResourceManager.GetString("ViewOfficialWebsite_PageTitle", resourceCulture);
            }
        }
    }
}
